tonkatsu-ika/freemarket_sample_62a

app/assets/javascripts/itmes.coffee, app/assets/stylesheets/itmes.scss, app/controllers/itmes_controller.rb, app/helpers/itmes_helper.rb, app/views/itmes/index.html.haml, config/routes.rb, spec/controllers/itmes_controller_spec.rb, spec/helpers/itmes_helper_spec.rb, spec/views/itmes/index.html.haml_spec.rb
ルーティングの設定とitemsコントローラの作成をした。
必要なため
=> [WIP]ルーティングの設定とコントローラを作成

app/controllers/items_controller.rb
=> indexアクションを追加

app/assets/stylesheets/modules/_header.scss, app/views/layouts/_header.html.haml
トップページのマークアップを行った。
以下の3要素にテンプレートを切り分けた
- ヘッダー
- メイン（商品一覧）
- フッター
注）メインもさらにテンプレート化可能なパーツが含まれているが、コーディングの効率性を考え、サーバサイドのロジックを組み上げた段階で実施する。
現段階では実装していない。
[動画](https://gyazo.com/0ddd745a991ce0f0e5181e3a258ffb34
)
[スクリーンショット](https://gyazo.com/d4537d623486b737f51fb5aa18e99a39
)
[スクリーンショット](https://gyazo.com/a4b667461c8ce6fdf702829bd4c4c27d
)
[スクリーンショット](https://gyazo.com/4c55b372747ceda80ddf02987c4dd99f
)
本アプリの主要なコンテンツであり重要なパーツであるため
=> 【マークアップ】トップページ

db/migrate/20191114071843_devise_create_users.rb, db/migrate/20191114073028_create_addresses.rb
=> マイグレーションファイルの修正

app/assets/stylesheets/modules/_userlogin.scss, app/views/devise/sessions/new.html.haml, app/views/layouts/users.html.haml, config/routes.rb, db/schema.rb
=> [WIP]Modifiy model

app/assets/stylesheets/config/_variables.scss, app/assets/stylesheets/mixin/_mixin.scss, app/assets/stylesheets/modules/mypage/_card.scss, app/assets/stylesheets/modules/mypage/_identification.scss, app/assets/stylesheets/modules/mypage/_logout.scss, app/views/mypage/_identification.html.haml
本人確認ページ(mypage)のマークアップを行いました。
***jQery***
未実装
***ビュー***
(上部)
https://gyazo.com/7944ff33cc4fcf33b225127efe1f5e13
(下部)
https://gyazo.com/e24654a53e74160a434769962a159312
マイページからの遷移先として必須なため。
=> 本人確認ページマークアップ

app/assets/stylesheets/modules/mypage/_profile.scss, app/views/mypage/_profile.html.haml
/mypage以下にあるユーザプロフィールページのマークアップを行った。
実装対象なし
https://gyazo.com/63c5c53e5e4eafdfd891c1e3428b0bca
ユーザが自身のプロフィールを編集するために必要なページであるため。
=> ユーザプロフィールページ（Mark-up)

app/assets/javascripts/items/new.js, app/assets/stylesheets/modules/items/_new.scss, app/controllers/items_controller.rb, app/models/address.rb, app/models/item.rb, app/views/items/new.html.haml, db/migrate/20191125080149_remove_prefecture_from_items.rb, db/migrate/20191125080416_add_prefecture_to_items.rb, db/schema.rb
商品出品のサーバーサイドを実装した。
アプリの根幹機能のため
=>  [WIP]商品出品のサーバーサイド

app/assets/javascripts/items/index.js, app/assets/javascripts/items/show.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_flash.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/item/_show.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/devise/sessions/new.html.haml, app/views/items/show.html.haml, app/views/layouts/_flash.html.haml, app/views/layouts/application.html.haml, db/schema.rb, spec/models/item_spec.rb, test/factories/categories.rb, test/factories/items.rb
出品した商品の削除機能を追加する。
出品を取り消したいときに必要なため。
=> [WIP]削除機能の追加

app/controllers/mypage_controller.rb, app/views/devise/sessions/new.html.haml, app/views/mypage/_identification.html.haml, app/views/mypage/_index.html.haml, app/views/mypage/_logout.html.haml
マイページを開いたときに、ログインユーザーのデータを反映する
データを更新するとき、全て入力し直さないようにするため
=> [WIP]マイページへ各種データを反映

README.md
itemテーブルの設計変更をする
開発を進めるにあたって、不都合が生じたため
=> [WIP]itemテーブルの設計変更

Gemfile, Gemfile.lock, app/assets/stylesheets/modules/_breadcrumb.scss, app/assets/stylesheets/modules/item/_show.scss, app/views/items/show.html.haml, app/views/layouts/_breadcrumb.html.haml, app/views/mypage/card.html.haml, app/views/mypage/identification.html.haml, app/views/mypage/index.html.haml, app/views/mypage/logout.html.haml, app/views/mypage/profile.html.haml, config/breadcrumbs.rb, config/routes.rb
パンくずリストを追加した
ユーザー自身が今どのページにいるかを可視化するため
=> [WIP]パンくずリストの追加

app/assets/stylesheets/modules/login/_registration.scss, app/controllers/signup_controller.rb, app/views/signup/address.html.haml
addressesテーブルのカラム名の変更に対応するため、collection_selectの属性名を変更。
=> prefectureをprefecture_idに変更

app/assets/javascripts/items/new.js, app/models/item.rb, app/views/items/edit.html.haml
=> カテゴリーの親子関係に関するif分の作成

app/assets/javascripts/items/index.js, app/assets/stylesheets/modules/login/_registration.scss, app/controllers/signup_controller.rb, app/views/items/index.html.haml, app/views/signup/registlation.html.haml
#what 
ユーザー新規登録時にエラーがあった場合にフラッシュメッセージを出力するよう作成
##why
リロード時に何のために、画面遷移があったのかわからないため
=> [WIP]ユーザー新規登録のフラッシュメッセージ作成

app/assets/stylesheets/modules/login/_registration.scss, app/controllers/signup_controller.rb, app/views/signup/registlation.html.haml
#what
ユーザ新規登録時のフラッシュメッセージを作成
#why
リロード時のアクションを制御するため
=> [WIP]フラッシュメッセージの作成(ユーザーの新規登録)

app/controllers/transactions_controller.rb, app/views/items/index/_men.html.haml, app/views/items/show.html.haml, app/views/transactions/show.html.haml, config/routes.rb
購入時のルーティングを修正する
現状のルーティングでは商品の情報を持ってこれないため
=> 購入時のルーティング修正

app/assets/javascripts/header/header.js, app/assets/stylesheets/modules/_header.scss, app/views/layouts/_header.html.haml, app/views/layouts/_mypagebar.html.haml, app/views/layouts/_noticebar.html.haml, app/views/layouts/_todobar.html.haml
jQeryでヘッダー、ユーザーメニューのリストを作成。
`
挙動のurlです
`
https://gyazo.com/3d6e755c260016b446263ca898655d87
=> ヘッダーメニュー(jQuery)

app/assets/stylesheets/modules/_index.scss, app/assets/stylesheets/modules/item/_show.scss, app/controllers/items_controller.rb, app/controllers/transactions_controller.rb, app/views/items/show.html.haml, app/views/layouts/basic.html.haml, app/views/transactions/show.html.haml
各ページへの遷移を条件によってわけ、エラーハンドリングを行なった。
ユーザーの情報は様々なパターンが考えられ、それらに対応したページ遷移する必要があるため
=> 購入、商品編集・削除の条件分岐

app/views/layouts/application.html.haml, app/views/mypage/_card.html.haml
=> 後からカード情報の登録ができるように記述を追加

app/assets/stylesheets/modules/items/_new.scss, app/views/devise/sessions/new.html.haml, app/views/items/new.html.haml, app/views/signup/address.html.haml, app/views/signup/auth.html.haml, app/views/signup/payment.html.haml, app/views/signup/registlation.html.haml, app/views/signup/sms_confirmation.html.haml
##what
軽微な修正
　・出品登録時のリンク
　・ログインボタン押下時登録するが出る
　・住所入力画面にて、翻訳しますかのメッセージの削除
　・recaptchaの削除
　・誕生日の選択日時のデフォルトを修正
##why
　UXを高めるため
=> [WIP]軽微な修正

app/assets/javascripts/header/category.js, app/assets/javascripts/header/header.js, app/assets/javascripts/slide_menu/slide_menu.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/header-list/_header-category.scss, app/assets/stylesheets/modules/slide_menu/_slide_brands.scss, app/controllers/application_controller.rb, app/views/layouts/_categorybar.html.haml, app/views/layouts/_categorychildren.html.haml, app/views/layouts/_categorygrand.html.haml, app/views/layouts/_header.html.haml, app/views/layouts/slide_menu/_slide_brands.html.haml
ヘッダーリストをjQueryで実装しました。
`挙動url`
https://gyazo.com/ba3bf8d934083c401eeccf85855fefe3
=> ヘッダーリスト実装(カテゴリー・ブランド)

app/controllers/application_controller.rb, config/deploy/production.rb
本番環境でBasic認証を実装した
アプリケーションの利用に制限をかけるため
=> 本番環境でBasic認証を実装

app/assets/javascripts/header/header.js, app/assets/stylesheets/modules/header-list/_header-category.scss, app/assets/stylesheets/modules/slide_menu/_slide_brands.scss, app/views/layouts/_header.html.haml
ヘッダーリスト（カテゴリ・ブランド）、レイアウト修正しました
=> ヘッダーリスト（カテゴリ・ブランド）、レイアウト修正

app/assets/stylesheets/modules/mypage/_like.scss, app/controllers/mypage_controller.rb, app/views/layouts/_header.html.haml, app/views/layouts/_sidebar_mypage.html.haml, app/views/mypage/_like.html.haml, app/views/mypage/_like_item.html.haml, app/views/mypage/like.html.haml, config/routes.rb
=> いいね一覧のview作成

app/controllers/mypage_controller.rb, app/models/user.rb, app/views/mypage/_profile.html.haml
##what
プロフィールの編集画面が表示される
##why
機能的に必要であるため
=> [WIP]プロフィールの編集が出力される:wq
